{% set version = "1.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rngtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rngtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rngtools/rngtools_{{ version }}.tar.gz
  sha256: 7f8c76ca4c7851b69a86e27be09b02ddc86357f0388659ef8787634682e8a74d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr
  run:
    - r-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr

test:
  commands:
    - $R -e "library('rngtools')"           # [not win]
    - "\"%R%\" -e \"library('rngtools')\""  # [win]

about:
  home: https://renozao.github.io/rngtools
  license: GPL-3
  summary: Provides a set of functions for working with Random Number Generators (RNGs). In particular, a generic S4 framework is defined for getting/setting the current RNG, or RNG data that are embedded into objects for reproducibility. Notably, convenient default methods greatly facilitate the way current RNG settings
    can be changed.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rngtools
# Authors@R:  c(person("Renaud", "Gaujoux", email = "renozao@protonmail.com", role = c("aut", "cre")), person("Max", "Kuhn", role = "ctb"))
# Version: 1.4
# License: GPL-3
# Title: Utility Functions for Working with Random Number Generators
# Description: Provides a set of functions for working with Random Number Generators (RNGs). In particular, a generic S4 framework is defined for getting/setting the current RNG, or RNG data that are embedded into objects for reproducibility. Notably, convenient default methods greatly facilitate the way current RNG settings can be changed.
# URL: https://renozao.github.io/rngtools
# BugReports: http://github.com/renozao/rngtools/issues
# Encoding: UTF-8
# Depends: R (>= 3.2.0), methods, pkgmaker (>= 0.20)
# Imports: stringr, digest, utils, stats, parallel
# Suggests: covr, RUnit, testthat
# Collate: 'rngtools-package.r' 'format.R' 'RNG.R' 'RNGseq.R'
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-01 22:19:39 UTC; jovyan
# Author: Renaud Gaujoux [aut, cre], Max Kuhn [ctb]
# Maintainer: Renaud Gaujoux <renozao@protonmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-01 23:00:03 UTC
