{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rngtools
  version: {{ version|replace("-", "_") }}

source:
  fn: rngtools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rngtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rngtools/rngtools_{{ version }}.tar.gz
  sha256: 763fc493cb821a4d3e514c0dc876d602a692c528e1d67f295dde70c77009e224

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr
  run:
    - r-base
    - r-digest
    - r-pkgmaker >=0.20
    - r-stringr

test:
  commands:
    - $R -e "library('rngtools')"           # [not win]
    - "\"%R%\" -e \"library('rngtools')\""  # [win]

about:
  home: https://renozao.github.io/rngtools
  license: GPL-3
  summary: Provides a set of functions for working with Random Number Generators (RNGs). In particular,
    a generic S4 framework is defined for getting/setting the current RNG, or RNG data
    that are embedded into objects for reproducibility. Notably, convenient default
    methods greatly facilitate the way current RNG settings can be changed.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
